=== LarsBauer/swe2/shop/src/test/resources/datasets/db.dtd
<!ELEMENT dataset (
    adresse*,
    artikel*,
    bestellposition*,
    bestellung*,
    bestellung_versand*,
    hibernate_sequence*,
    kreditkarte*,
    kunde*,
    versand*)>

<!ELEMENT adresse EMPTY>
<!ATTLIST adresse
    ad_id CDATA #REQUIRED
    plz CDATA #REQUIRED
    ort CDATA #REQUIRED
    strasse CDATA #IMPLIED
    hausnummer CDATA #IMPLIED
    kunde_fk CDATA #REQUIRED
    erzeugt CDATA #REQUIRED
    aktualisiert CDATA #REQUIRED
>

<!ELEMENT artikel EMPTY>
<!ATTLIST artikel
    a_id CDATA #REQUIRED
    name CDATA #REQUIRED
    preis CDATA #REQUIRED
    groesse CDATA #IMPLIED
    erzeugt CDATA #REQUIRED
    aktualisiert CDATA #REQUIRED
>

<!ELEMENT bestellposition EMPTY>
<!ATTLIST bestellposition
    bp_id CDATA #REQUIRED
    bestellung_fk CDATA #REQUIRED
    artikel_fk CDATA #REQUIRED
    anzahl CDATA #REQUIRED
    erzeugt CDATA #REQUIRED
    aktualisiert CDATA #REQUIRED
>

<!ELEMENT bestellung EMPTY>
<!ATTLIST bestellung
    b_id CDATA #REQUIRED
    kunde_fk CDATA #REQUIRED
    erzeugt CDATA #REQUIRED
    aktualisiert CDATA #REQUIRED
    status CDATA #IMPLIED
>

<!ELEMENT bestellung_versand EMPTY>
<!ATTLIST bestellung_versand
    bestellung_fk CDATA #REQUIRED
    versand_fk CDATA #REQUIRED
>

<!ELEMENT hibernate_sequence EMPTY>
<!ATTLIST hibernate_sequence
    next_val CDATA #REQUIRED
>

<!ELEMENT kreditkarte EMPTY>
<!ATTLIST kreditkarte
    kr_id CDATA #REQUIRED
    kreditkartennr CDATA #REQUIRED
    anbieter CDATA #REQUIRED
    sicherheitscode CDATA #REQUIRED
    gueltigbis CDATA #REQUIRED
    kunde_fk CDATA #REQUIRED
    erzeugt CDATA #REQUIRED
    aktualisiert CDATA #REQUIRED
>

<!ELEMENT kunde EMPTY>
<!ATTLIST kunde
    k_id CDATA #REQUIRED
    name CDATA #REQUIRED
    vorname CDATA #REQUIRED
    geschlecht CDATA #IMPLIED
    newsletter CDATA #REQUIRED
    email CDATA #REQUIRED
    passwort CDATA #REQUIRED
    erzeugt CDATA #REQUIRED
    aktualisiert CDATA #REQUIRED
>

<!ELEMENT versand EMPTY>
<!ATTLIST versand
    v_id CDATA #REQUIRED
    versandart CDATA #REQUIRED
    versandkosten CDATA #IMPLIED
    erzeugt CDATA #REQUIRED
    aktualisiert CDATA #REQUIRED
>

=== LarsBauer/swe2/shop/src/test/resources/datasets/db.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE dataset SYSTEM "db.dtd">
<dataset>
  <adresse ad_id="200" plz="76133" ort="Karlsruhe" strasse="Moltkestrasse" hausnummer="31" kunde_fk="100" erzeugt="2006-08-01 00:00:00.0" aktualisiert="2006-08-01 00:00:00.0"/>
  <adresse ad_id="201" plz="76133" ort="Karlsruhe" strasse="Moltkestrasse" hausnummer="32" kunde_fk="101" erzeugt="2006-08-02 00:00:00.0" aktualisiert="2006-08-02 00:00:00.0"/>
  <adresse ad_id="202" plz="76133" ort="Karlsruhe" strasse="Moltkestrasse" hausnummer="33" kunde_fk="102" erzeugt="2006-08-03 00:00:00.0" aktualisiert="2006-08-03 00:00:00.0"/>
  <adresse ad_id="203" plz="76133" ort="Karlsruhe" strasse="Moltkestrasse" hausnummer="34" kunde_fk="103" erzeugt="2006-08-04 00:00:00.0" aktualisiert="2006-08-04 00:00:00.0"/>
  <adresse ad_id="204" plz="76133" ort="Karlsruhe" strasse="Moltkestrasse" hausnummer="35" kunde_fk="104" erzeugt="2006-08-05 00:00:00.0" aktualisiert="2006-08-05 00:00:00.0"/>
  <artikel a_id="300" name="Hose" preis="80.0" groesse="M" erzeugt="2006-08-01 00:00:00.0" aktualisiert="2006-08-01 00:00:00.0"/>
  <artikel a_id="301" name="Schuhe" preis="10.0" groesse="XL" erzeugt="2006-08-02 00:00:00.0" aktualisiert="2006-08-02 00:00:00.0"/>
  <artikel a_id="302" name="Pullover" preis="300.0" groesse="L" erzeugt="2006-08-03 00:00:00.0" aktualisiert="2006-08-03 00:00:00.0"/>
  <artikel a_id="303" name="T-Shirt" preis="150.0" groesse="L" erzeugt="2006-08-04 00:00:00.0" aktualisiert="2006-08-04 00:00:00.0"/>
  <artikel a_id="304" name="Socken" preis="60.0" groesse="S" erzeugt="2006-08-05 00:00:00.0" aktualisiert="2006-08-05 00:00:00.0"/>
  <artikel a_id="305" name="Unterwäsche" preis="500.0" groesse="XS" erzeugt="2006-08-06 00:00:00.0" aktualisiert="2006-08-06 00:00:00.0"/>
  <artikel a_id="306" name="Hut" preis="600.0" groesse="M" erzeugt="2006-08-07 00:00:00.0" aktualisiert="2006-08-07 00:00:00.0"/>
  <bestellposition bp_id="500" bestellung_fk="400" artikel_fk="300" anzahl="1"/>
  <bestellposition bp_id="501" bestellung_fk="400" artikel_fk="301" anzahl="4"/>
  <bestellposition bp_id="502" bestellung_fk="401" artikel_fk="302" anzahl="5"/>
  <bestellposition bp_id="503" bestellung_fk="402" artikel_fk="303" anzahl="3"/>
  <bestellposition bp_id="504" bestellung_fk="402" artikel_fk="304" anzahl="2"/>
  <bestellposition bp_id="505" bestellung_fk="403" artikel_fk="305" anzahl="1"/>
  <bestellposition bp_id="506" bestellung_fk="404" artikel_fk="300" anzahl="5"/>
  <bestellposition bp_id="507" bestellung_fk="404" artikel_fk="301" anzahl="2"/>
  <bestellposition bp_id="508" bestellung_fk="404" artikel_fk="302" anzahl="8"/>
  <bestellung b_id="400" kunde_fk="100" erzeugt="2006-08-01 00:00:00.0" aktualisiert="2006-08-01 00:00:00.0" status="in Bearbeitung"/>
  <bestellung b_id="401" kunde_fk="100" erzeugt="2006-08-02 00:00:00.0" aktualisiert="2006-08-02 00:00:00.0" status="versendet"/>
  <bestellung b_id="402" kunde_fk="101" erzeugt="2006-08-03 00:00:00.0" aktualisiert="2006-08-03 00:00:00.0" status="versendet"/>
  <bestellung b_id="403" kunde_fk="101" erzeugt="2006-08-04 00:00:00.0" aktualisiert="2006-08-04 00:00:00.0" status="auf Bezahlung warten"/>
  <bestellung b_id="404" kunde_fk="103" erzeugt="2006-08-05 00:00:00.0" aktualisiert="2006-08-05 00:00:00.0" status="storniert"/>
  <bestellung_versand bestellung_fk="400" versand_fk="600"/>
  <bestellung_versand bestellung_fk="401" versand_fk="600"/>
  <bestellung_versand bestellung_fk="402" versand_fk="601"/>
  <bestellung_versand bestellung_fk="402" versand_fk="602"/>
  <bestellung_versand bestellung_fk="403" versand_fk="602"/>
  <bestellung_versand bestellung_fk="404" versand_fk="603"/>
  <hibernate_sequence next_val="5000"/>
  <kreditkarte kr_id="1" kreditkartennr="1234567890123" anbieter="Visa" sicherheitscode="167" gueltigbis="05/13" kunde_fk="100" erzeugt="2006-08-01 00:00:00.0" aktualisiert="2006-08-01 00:00:00.0"/>
  <kreditkarte kr_id="2" kreditkartennr="098765432172" anbieter="Mastercard" sicherheitscode="156" gueltigbis="09/16" kunde_fk="101" erzeugt="2006-08-02 00:00:00.0" aktualisiert="2006-08-02 00:00:00.0"/>
  <kunde k_id="100" name="Alpha" vorname="Adrian" geschlecht="0" newsletter="true" email="1@hska.de" passwort="100" erzeugt="2006-08-01 00:00:00.0" aktualisiert="2006-08-01 00:00:00.0"/>
  <kunde k_id="101" name="Alpha" vorname="Alfred" geschlecht="0" newsletter="true" email="k2@hska.de" passwort="101" erzeugt="2006-08-02 00:00:00.0" aktualisiert="2006-08-02 00:00:00.0"/>
  <kunde k_id="102" name="Alpha" vorname="Anton" newsletter="false" email="k3@hska.de" passwort="102" erzeugt="2006-08-03 00:00:00.0" aktualisiert="2006-08-03 00:00:00.0"/>
  <kunde k_id="103" name="Delta" vorname="Dirk" newsletter="true" email="k4@hska.de" passwort="103" erzeugt="2006-08-04 00:00:00.0" aktualisiert="2006-08-04 00:00:00.0"/>
  <kunde k_id="104" name="Epsilon" vorname="Emil" geschlecht="0" newsletter="false" email="k5@hska.de" passwort="104" erzeugt="2006-08-05 00:00:00.0" aktualisiert="2006-08-05 00:00:00.0"/>
  <versand v_id="600" versandart="Paket" versandkosten="6.9" erzeugt="2012-10-22 17:32:00.0" aktualisiert="2012-10-22 17:32:00.0"/>
  <versand v_id="601" versandart="Päckchen" versandkosten="4.5" erzeugt="2012-10-22 17:32:00.0" aktualisiert="2012-10-22 17:32:00.0"/>
  <versand v_id="602" versandart="Warensendung" versandkosten="1.65" erzeugt="2012-10-22 17:32:00.0" aktualisiert="2012-10-22 17:32:00.0"/>
  <versand v_id="603" versandart="Einschreiben" versandkosten="2.9" erzeugt="2012-10-22 17:32:00.0" aktualisiert="2012-10-22 17:32:00.0"/>
</dataset>
